spring.application.name=digitalservices
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_services_db
spring.datasource.username=postgres
spring.datasource.password=moise

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect